name: Deploy

on:
  push:
    branches:
      - master

#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: akhileshns/heroku-deploy@v3.8.8 # This is the action
#        with:
#          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
#          heroku_app_name: "ymath" #Must be unique in Heroku
#          heroku_email: "saumyasmathtutoring@gmail.com"
          



jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Updating Ubuntu system and Heroku
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: sudo apt update && sudo apt install heroku neofetch
      - name: Checking the info
        run: neofetch

      - uses: akhileshns/heroku-deploy@v3.8.8
        with:
          heroku_email: saumyasmathtutoring@gmail.com
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ymath
          branch: HEAD
          useforce: false
          dynamicFiles: false

